### ISSUE TITLE
I got this problem, since a few days. Can anyone help me? 

### ISSUE THREAD

**Issue by moitzfeld** [py-smart-gardena/hass-gardena-smart-system#196]
Logger: homeassistant.setup
Source: setup.py:221
First occurred: 16:13:56 (1 occurrences)
Last logged: 16:13:56

Setup failed for custom integration 'gardena_smart_system': Requirements for gardena_smart_system not found: ['py-smart-gardena==1.3.7'].

**Comment by moitzfeld** [comment]
I have restartet the system, deactivate it but can#t delet it

**Comment by JohnBull-1975** [comment]
Same here

Updated to 2024.2.1 and now my Gardena Integration fails to load:

Invalid config

Logger: homeassistant.setup
Source: setup.py:221
First occurred: 18:04:01 (1 occurrences)
Last logged: 18:04:01

Setup failed for custom integration 'gardena_smart_system': Requirements for gardena_smart_system not found: ['py-smart-gardena==1.3.7'].

Logger: homeassistant.util.package
Source: util/package.py:122
First occurred: 18:03:55 (3 occurrences)
Last logged: 18:04:01

Unable to install package py-smart-gardena==1.3.7: error: subprocess-exited-with-error × python setup.py egg_info did not run successfully. │ exit code: 1 ╰─> [18 lines of output] /tmp/pip-install-uiz028ln/py-smart-gardena_e3dee4b62ba84651ab7eae5d07d7b4ea/versioneer.py:421: SyntaxWarning: invalid escape sequence '\s' LONG_VERSION_PY['git'] = ''' Traceback (most recent call last): File "<string>", line 2, in <module> File "<pip-setuptools-caller>", line 34, in <module> File "/tmp/pip-install-uiz028ln/py-smart-gardena_e3dee4b62ba84651ab7eae5d07d7b4ea/setup.py", line 16, in <module> version=versioneer.get_version(), ^^^^^^^^^^^^^^^^^^^^^^^^ File "/tmp/pip-install-uiz028ln/py-smart-gardena_e3dee4b62ba84651ab7eae5d07d7b4ea/versioneer.py", line 1480, in get_version return get_versions()["version"] ^^^^^^^^^^^^^^ File "/tmp/pip-install-uiz028ln/py-smart-gardena_e3dee4b62ba84651ab7eae5d07d7b4ea/versioneer.py", line 1412, in get_versions cfg = get_config_from_root(root) ^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/tmp/pip-install-uiz028ln/py-smart-gardena_e3dee4b62ba84651ab7eae5d07d7b4ea/versioneer.py", line 342, in get_config_from_root parser = configparser.SafeConfigParser() ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'? [end of output] note: This error originates from a subprocess, and is likely not a problem with pip. error: metadata-generation-failed × Encountered error while generating package metadata. ╰─> See above for output. note: This is an issue with the package mentioned above, not pip. hint: See above for details.
Unable to install package py-smart-gardena==1.3.7: error: subprocess-exited-with-error × python setup.py egg_info did not run successfully. │ exit code: 1 ╰─> [18 lines of output] /tmp/pip-install-8kpyg3tz/py-smart-gardena_0289dde29c6e43d2a48430bcdf7e1a4d/versioneer.py:421: SyntaxWarning: invalid escape sequence '\s' LONG_VERSION_PY['git'] = ''' Traceback (most recent call last): File "<string>", line 2, in <module> File "<pip-setuptools-caller>", line 34, in <module> File "/tmp/pip-install-8kpyg3tz/py-smart-gardena_0289dde29c6e43d2a48430bcdf7e1a4d/setup.py", line 16, in <module> version=versioneer.get_version(), ^^^^^^^^^^^^^^^^^^^^^^^^ File "/tmp/pip-install-8kpyg3tz/py-smart-gardena_0289dde29c6e43d2a48430bcdf7e1a4d/versioneer.py", line 1480, in get_version return get_versions()["version"] ^^^^^^^^^^^^^^ File "/tmp/pip-install-8kpyg3tz/py-smart-gardena_0289dde29c6e43d2a48430bcdf7e1a4d/versioneer.py", line 1412, in get_versions cfg = get_config_from_root(root) ^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/tmp/pip-install-8kpyg3tz/py-smart-gardena_0289dde29c6e43d2a48430bcdf7e1a4d/versioneer.py", line 342, in get_config_from_root parser = configparser.SafeConfigParser() ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'? [end of output] note: This error originates from a subprocess, and is likely not a problem with pip. error: metadata-generation-failed × Encountered error while generating package metadata. ╰─> See above for output. note: This is an issue with the package mentioned above, not pip. hint: See above for details.
Unable to install package py-smart-gardena==1.3.7: error: subprocess-exited-with-error × python setup.py egg_info did not run successfully. │ exit code: 1 ╰─> [18 lines of output] /tmp/pip-install-uwxikw6c/py-smart-gardena_d12b4b2c4d0347cebd0dea13f156f5d2/versioneer.py:421: SyntaxWarning: invalid escape sequence '\s' LONG_VERSION_PY['git'] = ''' Traceback (most recent call last): File "<string>", line 2, in <module> File "<pip-setuptools-caller>", line 34, in <module> File "/tmp/pip-install-uwxikw6c/py-smart-gardena_d12b4b2c4d0347cebd0dea13f156f5d2/setup.py", line 16, in <module> version=versioneer.get_version(), ^^^^^^^^^^^^^^^^^^^^^^^^ File "/tmp/pip-install-uwxikw6c/py-smart-gardena_d12b4b2c4d0347cebd0dea13f156f5d2/versioneer.py", line 1480, in get_version return get_versions()["version"] ^^^^^^^^^^^^^^ File "/tmp/pip-install-uwxikw6c/py-smart-gardena_d12b4b2c4d0347cebd0dea13f156f5d2/versioneer.py", line 1412, in get_versions cfg = get_config_from_root(root) ^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/tmp/pip-install-uwxikw6c/py-smart-gardena_d12b4b2c4d0347cebd0dea13f156f5d2/versioneer.py", line 342, in get_config_from_root parser = configparser.SafeConfigParser() ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'? [end of output] note: This error originates from a subprocess, and is likely not a problem with pip. error: metadata-generation-failed × Encountered error while generating package metadata. ╰─> See above for output. note: This is an issue with the package mentioned above, not pip. hint: See above for details.

**Comment by JohnBull-1975** [comment]
on the github page I saw this:
"⚠️ Starting from version 1.0.0b5: You might probably have to uninstall and reinstall the integration as credentials requirements and method has changed. THERE IS A BREAKING CHANGE IN THE CONFIGURATION DUE TO AN UPDATE ON THE GARDENA API"
But it looks to be 1.0.0 that is current version. What is b5 and when is this comment added?

Will it help to uninstall and reinstall? Don't really have the time right now and need to backup all entity names etc first...

**Comment by grm** [comment]
It shoud work with latest release 1.1.0.

Can you give it a try ?

**Comment by moitzfeld** [comment]
It worked with the version 1.1.0Thanks a lot Am 10.02.2024 um 23:31 schrieb Jérémie Klein ***@***.***>:﻿
It shoud work with latest release 1.1.0.
Can you give it a try ?

**Comment by grm** [comment]
You are welcome :)

**Comment by JohnBull-1975** [comment]
updated now and it works!
THANKS!
