### ISSUE TITLE
Hassio 0.115.0 breaks integration

### ISSUE THREAD

**Issue by LucTs** [py-smart-gardena/hass-gardena-smart-system#43]
Hi,

after I updated to 0.115.0 Gardena integration is not working anymore.

After restart of Hassio it says:
_The following integrations and platforms could not be set up:

    gardena_smart_system.sensor
    gardena_smart_system.switch
    gardena_smart_system.vacuum

Please check your config._

Within the logs I found:
```
Logger: homeassistant.setup
Source: setup.py:280
First occurred: 19:47:29 (3 occurrences)
Last logged: 19:47:31

    Unable to prepare setup for platform gardena_smart_system.sensor: Platform not found (cannot import name 'UNIT_PERCENTAGE' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)).
    Unable to prepare setup for platform gardena_smart_system.switch: Platform not found (cannot import name 'UNIT_PERCENTAGE' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)).
    Unable to prepare setup for platform gardena_smart_system.vacuum: Platform not found (cannot import name 'UNIT_PERCENTAGE' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)).
```

**Comment by sashgithub** [comment]
I have the same issue.

**Comment by northpower25** [comment]
Me too

**Comment by grm** [comment]
Hello,

I will update my home assistant to check what is the issue. I ll try to do
that this week end !

Jeremie

Le jeu. 17 sept. 2020 à 21:52, northpower25 <notifications@github.com> a
écrit :

**Comment by StephanU** [comment]
I'm citing somebody from the HomeAssistant 0.115 release page:

> UNIT_PERCENTAGE was changed to PERCENTAGE in 0.115.

**Comment by northpower25** [comment]
Her the explanation for this problem -> https://github.com/home-assistant/core/pull/39383

**Comment by FlavorFx** [comment]
The fix works properly. Well done and thx.

**Comment by fabsenet** [comment]
can we merge the PR and release it?
