### PR TITLE
Update for HomeAssistant 0.115

### LINKED ISSUE #43: Hassio 0.115.0 breaks integration
Hi,

after I updated to 0.115.0 Gardena integration is not working anymore.

After restart of Hassio it says:
_The following integrations and platforms could not be set up:

    gardena_smart_system.sensor
    gardena_smart_system.switch
    gardena_smart_system.vacuum

Please check your config._

Within the logs I found:
```
Logger: homeassistant.setup
Source: setup.py:280
First occurred: 19:47:29 (3 occurrences)
Last logged: 19:47:31

    Unable to prepare setup for platform gardena_smart_system.sensor: Platform not found (cannot import name 'UNIT_PERCENTAGE' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)).
    Unable to prepare setup for platform gardena_smart_system.switch: Platform not found (cannot import name 'UNIT_PERCENTAGE' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)).
    Unable to prepare setup for platform gardena_smart_system.vacuum: Platform not found (cannot import name 'UNIT_PERCENTAGE' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)).
```

### PR DESCRIPTION
**Pull request by StephanU**
Change UNIT_PERCENTAGE to PERCENTAGE due to change in Homeassistant 0.115
Fixes #43

### CODE REVIEW

**Review by northpower25 — APPROVED** [review]
Now it works with HA 0.115.0

**Comment by Jpsy** [comment]
I can confirm that this PR restores functionality of the integration with HA 0.115.
Thanks @StephanU !

**Review by Jpsy — APPROVED** [review]

**Comment by StephanU** [comment]
@Jpsy  You seem to have made changes to this repo in the past... do you have write permissions to merge this PR?

**Comment by grm** [comment]
I am on merging, no worries ;)

**Comment by grm** [comment]
Seems fine to me.
I merge

**Comment by grm** [comment]
I just pushed a new 0.2.2b1 version in beta. Could you give t a try and confirm that it works for you ?

**Comment by abey79** [comment]
It works for me.
