### ISSUE TITLE
error release 1.0.0. + HA + Gardera Sileno mower (working in 1.0.0-0b907)

### ISSUE THREAD

**Issue by kalonly** [py-smart-gardena/hass-gardena-smart-system#153]
When integrating a Gardena Mower smart SILENO life (artnr  19701-66) in Home Assistant with the latest release 1.0.0. I'll get this error: ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform gardena_smart_system.vacuum: Platform not found (cannot import name 'UnitOfTemperature' from 'homeassistant.components.sensor' (/usr/src/homeassistant/homeassistant/components/sensor/__init__.py)).

After downgrading / reinstalling 1.0.0.0b907 the Gardena integration is working again (showing device and battery status).

**Comment by grm** [comment]
Thx for the report !

Which version of Home assistant are you using ?

Jérémie

**Comment by tanderloco** [comment]
I have the same issue and it applies to all services: the mowers (vacuums), sensors and switches. 
Version is 2022.12.9.

Logger: homeassistant.setup
Source: setup.py:338
First occurred: 25. januar 2023 kl. 21:29:23 (3 occurrences)
Last logged: 25. januar 2023 kl. 21:29:23

Unable to prepare setup for platform gardena_smart_system.sensor: Platform not found (cannot import name 'UnitOfTemperature' from 'homeassistant.components.sensor' (/usr/src/homeassistant/homeassistant/components/sensor/__init__.py)).
Unable to prepare setup for platform gardena_smart_system.switch: Platform not found (cannot import name 'UnitOfTemperature' from 'homeassistant.components.sensor' (/usr/src/homeassistant/homeassistant/components/sensor/__init__.py)).
Unable to prepare setup for platform gardena_smart_system.vacuum: Platform not found (cannot import name 'UnitOfTemperature' from 'homeassistant.components.sensor' (/usr/src/homeassistant/homeassistant/components/sensor/__init__.py)).

**Comment by kalonly** [comment]
Home Assistant 2022.10.5

Frontend 20221010.0 - latest

 

Van: Jérémie Klein ***@***.***> 
Verzonden: donderdag 26 januari 2023 15:56
Aan: py-smart-gardena/hass-gardena-smart-system ***@***.***>
CC: kalonly ***@***.***>; Author ***@***.***>
Onderwerp: Re: [py-smart-gardena/hass-gardena-smart-system] error release 1.0.0. + HA + Gardera Sileno mower (working in 1.0.0-0b907) (Issue #153)

 

Thx for the report !

Which version of Home assistant are you using ?

Jérémie

**Comment by grm** [comment]
Hello,

could you try update to at least version 2023.1.5 ? 
I think there was a breaking change in home assistant API as it is working on my side !

I'll update the package if the plugin requires a minimum home assistant version

**Comment by kalonly** [comment]
Tested 1.0.0. with Home Assistant 2023.1.7 & Frontend 20230110.0 - latest (start, stop, return home, attributes)

No issues with this version of HA

**Comment by grm** [comment]
Great. 
I ill force a minimum version for the new release !

Thx for the report
