### ISSUE TITLE
get error when adding integration

### ISSUE THREAD

**Issue by StartDustTC** [py-smart-gardena/hass-gardena-smart-system#197]
Installation via HACS was fine.
When adding the integration through settings, I get a 500 error: 500 Internal Server Error Server got itself in trouble

This is from the log...
Logger: homeassistant.util.package
Source: util/package.py:122
First occurred: 19:22:07 (3 occurrences)
Last logged: 19:22:33

    Unable to install package py-smart-gardena==1.3.7: error: subprocess-exited-with-error × python setup.py egg_info did not run successfully. │ exit code: 1 ╰─> [18 lines of output] /tmp/pip-install-7s2h02z_/py-smart-gardena_d3895bbd9cac4d338b148521122074e4/versioneer.py:421: SyntaxWarning: invalid escape sequence '\s' LONG_VERSION_PY['git'] = ''' Traceback (most recent call last): File "<string>", line 2, in <module> File "<pip-setuptools-caller>", line 34, in <module> File "/tmp/pip-install-7s2h02z_/py-smart-gardena_d3895bbd9cac4d338b148521122074e4/setup.py", line 16, in <module> version=versioneer.get_version(), ^^^^^^^^^^^^^^^^^^^^^^^^ File "/tmp/pip-install-7s2h02z_/py-smart-gardena_d3895bbd9cac4d338b148521122074e4/versioneer.py", line 1480, in get_version return get_versions()["version"] ^^^^^^^^^^^^^^ File "/tmp/pip-install-7s2h02z_/py-smart-gardena_d3895bbd9cac4d338b148521122074e4/versioneer.py", line 1412, in get_versions cfg = get_config_from_root(root) ^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/tmp/pip-install-7s2h02z_/py-smart-gardena_d3895bbd9cac4d338b148521122074e4/versioneer.py", line 342, in get_config_from_root parser = configparser.SafeConfigParser() ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'? [end of output] note: This error originates from a subprocess, and is likely not a problem with pip. error: metadata-generation-failed × Encountered error while generating package metadata. ╰─> See above for output. note: This is an issue with the package mentioned above, not pip. hint: See above for details.
    Unable to install package py-smart-gardena==1.3.7: error: subprocess-exited-with-error × python setup.py egg_info did not run successfully. │ exit code: 1 ╰─> [18 lines of output] /tmp/pip-install-3nl9vsyj/py-smart-gardena_c453feb2eeda4159879ab40ee7db951e/versioneer.py:421: SyntaxWarning: invalid escape sequence '\s' LONG_VERSION_PY['git'] = ''' Traceback (most recent call last): File "<string>", line 2, in <module> File "<pip-setuptools-caller>", line 34, in <module> File "/tmp/pip-install-3nl9vsyj/py-smart-gardena_c453feb2eeda4159879ab40ee7db951e/setup.py", line 16, in <module> version=versioneer.get_version(), ^^^^^^^^^^^^^^^^^^^^^^^^ File "/tmp/pip-install-3nl9vsyj/py-smart-gardena_c453feb2eeda4159879ab40ee7db951e/versioneer.py", line 1480, in get_version return get_versions()["version"] ^^^^^^^^^^^^^^ File "/tmp/pip-install-3nl9vsyj/py-smart-gardena_c453feb2eeda4159879ab40ee7db951e/versioneer.py", line 1412, in get_versions cfg = get_config_from_root(root) ^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/tmp/pip-install-3nl9vsyj/py-smart-gardena_c453feb2eeda4159879ab40ee7db951e/versioneer.py", line 342, in get_config_from_root parser = configparser.SafeConfigParser() ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'? [end of output] note: This error originates from a subprocess, and is likely not a problem with pip. error: metadata-generation-failed × Encountered error while generating package metadata. ╰─> See above for output. note: This is an issue with the package mentioned above, not pip. hint: See above for details.
    Unable to install package py-smart-gardena==1.3.7: error: subprocess-exited-with-error × python setup.py egg_info did not run successfully. │ exit code: 1 ╰─> [18 lines of output] /tmp/pip-install-8cqafd6u/py-smart-gardena_daf21bde57af49c7a292737285b86d67/versioneer.py:421: SyntaxWarning: invalid escape sequence '\s' LONG_VERSION_PY['git'] = ''' Traceback (most recent call last): File "<string>", line 2, in <module> File "<pip-setuptools-caller>", line 34, in <module> File "/tmp/pip-install-8cqafd6u/py-smart-gardena_daf21bde57af49c7a292737285b86d67/setup.py", line 16, in <module> version=versioneer.get_version(), ^^^^^^^^^^^^^^^^^^^^^^^^ File "/tmp/pip-install-8cqafd6u/py-smart-gardena_daf21bde57af49c7a292737285b86d67/versioneer.py", line 1480, in get_version return get_versions()["version"] ^^^^^^^^^^^^^^ File "/tmp/pip-install-8cqafd6u/py-smart-gardena_daf21bde57af49c7a292737285b86d67/versioneer.py", line 1412, in get_versions cfg = get_config_from_root(root) ^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/tmp/pip-install-8cqafd6u/py-smart-gardena_daf21bde57af49c7a292737285b86d67/versioneer.py", line 342, in get_config_from_root parser = configparser.SafeConfigParser() ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'? [end of output] note: This error originates from a subprocess, and is likely not a problem with pip. error: metadata-generation-failed × Encountered error while generating package metadata. ╰─> See above for output. note: This is an issue with the package mentioned above, not pip. hint: See above for details.

**Comment by grm** [comment]
It shoud work with latest release 1.1.0.

Can you give it a try ?

**Comment by helmut-hackl** [comment]
> It shoud work with latest release 1.1.0.
> 
> Can you give it a try ?

Tested and works like a charm again! Thank you for fixing this and thank you for your time. May I buy you a coffee in any way ...

**Comment by StartDustTC** [comment]
Cool, thank you. It was working fine with 1.1.0!

**Comment by mercslkamg** [comment]
Saw the update today. Great everything ok now with CORE 2024.2.1
Many thanks for the fix.
