### ISSUE TITLE
Sensor not updated

### ISSUE THREAD

**Issue by tonioa** [py-smart-gardena/hass-gardena-smart-system#88]
Hi,

Since updated on version 2021.7.4

My Sensor are not updated since i restart Home Assistant, here is the error on the log.

2021-08-10 14:43:47 ERROR (Thread-3) [websocket] error from callback <bound method Client.on_message of <gardena.smart_system.Client object at 0x7f645d14bfd0>>: on_message() takes 2 positional arguments but 3 were given
2021-08-10 14:43:47 ERROR (Thread-3) [websocket] error from callback <bound method Client.on_message of <gardena.smart_system.Client object at 0x7f645d14bfd0>>: on_message() takes 2 positional arguments but 3 were given
2021-08-10 14:43:47 ERROR (Thread-3) [websocket] error from callback <bound method Client.on_message of <gardena.smart_system.Client object at 0x7f645d14bfd0>>: on_message() takes 2 positional arguments but 3 were given
2021-08-10 14:43:47 ERROR (Thread-3) [websocket] error from callback <bound method Client.on_message of <gardena.smart_system.Client object at 0x7f645d14bfd0>>: on_message() takes 2 positional arguments but 3 were given
2021-08-10 14:43:47 ERROR (Thread-3) [websocket] error from callback <bound method Client.on_message of <gardena.smart_system.Client object at 0x7f645d14bfd0>>: on_message() takes 2 positional arguments but 3 were given
2021-08-10 14:43:47 ERROR (Thread-3) [websocket] error from callback <bound method Client.on_message of <gardena.smart_system.Client object at 0x7f645d14bfd0>>: on_message() takes 2 positional arguments but 3 were given
2021-08-10 14:43:47 ERROR (Thread-3) [websocket] error from callback <bound method Client.on_message of <gardena.smart_system.Client object at 0x7f645d14bfd0>>: on_message() takes 2 positional arguments but 3 were given
2021-08-10 14:43:47 ERROR (Thread-3) [websocket] error from callback <bound method Client.on_message of <gardena.smart_system.Client object at 0x7f645d14bfd0>>: on_message() takes 2 positional arguments but 3 were given

**Comment by ElBalsero** [comment]
Exactly the same problem here when updating from 2021.6.6 to 2021.8.5.
Same bunch of errors and then the status of the sensors is not updated anymore.

**Comment by GG-Style** [comment]
I have the same Problem

**Comment by grm** [comment]
Hello,

I am currently on hlidays with poor internet access ! I will try to publish
a patch soon !

Jeremie

Le jeu. 12 août 2021 à 15:21, Mickaël Moreira ***@***.***> a
écrit :

**Comment by LordTama** [comment]
> Hello, I am currently on hlidays with poor internet access ! I will try to publish a patch soon ! Jeremie Le jeu. 12 août 2021 à 15:21, Mickaël Moreira ***@***.***> a écrit :
> […](#)

Sorry I was not aware of this. Good holiday :)

**Comment by erikkt** [comment]
I get the following error: 
2021-08-16 11:01:38 ERROR (Thread-3) [gardena.smart_system] error : 'Thread' object has no attribute 'isAlive'

Is this related, or should I open a new issue?

**Comment by 4speri** [comment]
I’m having the same issue. Hopefully soon fixed. I’m using this integration to control the heater in my wife’s greenhouse and it’s starting to get cold here in Sweden. Thanks in advance!!

**Comment by tonioa** [comment]
Updating to gardena integration beta version 0.2.5b3 solved the issue for me too.

**Comment by 4speri** [comment]
Yeah it seems like 0.2.5b3 solved this issue.

**Comment by erikkt** [comment]
0.2.5b3 did not solve the issue for me.

**Comment by fjepsen** [comment]
I also installed 0.2.5b3 and after a restart everything seemed to work. I was able to switch one of my sockets on/off multiple times and its state got updated and my mower also sent its state. But some minutes later again no updates. Here is the log of it:

> 2021-09-03 17:44:46 INFO (MainThread) [custom_components.hacs] Stage changed: HacsStage.RUNNING
2021-09-03 17:44:59 DEBUG (Thread-3) [gardena.smart_system] Received POWER_SOCKET message
2021-09-03 17:44:59 DEBUG (Thread-3) [gardena.smart_system] ------- Beginning of message ---------
2021-09-03 17:44:59 DEBUG (Thread-3) [gardena.smart_system] {"id":"28fa6df0-2a6d-4443-82a2-f3aa6b16c655","type":"POWER_SOCKET","attributes":{"activity":{"value":"OFF","timestamp":"2021-09-03T15:44:59.595+0000"},"state":{"value":"OK","timestamp":"2021-08-30T17:45:56.389+0000"}}}
2021-09-03 17:44:59 DEBUG (Thread-3) [gardena.smart_system] ------- End of message ---------
2021-09-03 17:44:59 DEBUG (Thread-3) [gardena.smart_system] Received COMMON message
2021-09-03 17:44:59 DEBUG (Thread-3) [gardena.smart_system] ------- Beginning of message ---------
2021-09-03 17:44:59 DEBUG (Thread-3) [gardena.smart_system] {"id":"28fa6df0-2a6d-4443-82a2-f3aa6b16c655","type":"COMMON","attributes":{"name":{"value":"SPower1"},"batteryState":{"value":"NO_BATTERY"},"rfLinkLevel":{"value":80,"timestamp":"2021-09-03T15:33:44.671+0000"},"serial":{"value":"00029416"},"modelType":{"value":"GARDENA smart Power"},"rfLinkState":{"value":"ONLINE"}}}
2021-09-03 17:44:59 DEBUG (Thread-3) [gardena.smart_system] ------- End of message ---------
2021-09-03 17:44:59 DEBUG (MainThread) [custom_components.gardena_smart_system.switch] Running Gardena update
2021-09-03 17:44:59 DEBUG (MainThread) [custom_components.gardena_smart_system.switch] Power socket has state OK
2021-09-03 17:44:59 DEBUG (MainThread) [custom_components.gardena_smart_system.switch] Getting Power socket state
2021-09-03 17:44:59 DEBUG (MainThread) [custom_components.gardena_smart_system.switch] Power socket has activity OFF
2021-09-03 17:45:04 DEBUG (Thread-3) [gardena.smart_system] Received POWER_SOCKET message
2021-09-03 17:45:04 DEBUG (Thread-3) [gardena.smart_system] ------- Beginning of message ---------
2021-09-03 17:45:04 DEBUG (Thread-3) [gardena.smart_system] {"id":"28fa6df0-2a6d-4443-82a2-f3aa6b16c655","type":"POWER_SOCKET","attributes":{"activity":{"value":"FOREVER_ON","timestamp":"2021-09-03T15:45:03.947+0000"},"state":{"value":"OK","timestamp":"2021-08-30T17:45:56.389+0000"}}}
2021-09-03 17:45:04 DEBUG (Thread-3) [gardena.smart_system] ------- End of message ---------
2021-09-03 17:45:04 DEBUG (Thread-3) [gardena.smart_system] Received COMMON message
2021-09-03 17:45:04 DEBUG (Thread-3) [gardena.smart_system] ------- Beginning of message ---------
2021-09-03 17:45:04 DEBUG (Thread-3) [gardena.smart_system] {"id":"28fa6df0-2a6d-4443-82a2-f3aa6b16c655","type":"COMMON","attributes":{"name":{"value":"SPower1"},"batteryState":{"value":"NO_BATTERY"},"rfLinkLevel":{"value":80,"timestamp":"2021-09-03T15:33:44.671+0000"},"serial":{"value":"00029416"},"modelType":{"value":"GARDENA smart Power"},"rfLinkState":{"value":"ONLINE"}}}
2021-09-03 17:45:04 DEBUG (Thread-3) [gardena.smart_system] ------- End of message ---------
2021-09-03 17:45:04 DEBUG (MainThread) [custom_components.gardena_smart_system.switch] Running Gardena update
2021-09-03 17:45:04 DEBUG (MainThread) [custom_components.gardena_smart_system.switch] Power socket has state OK
2021-09-03 17:45:04 DEBUG (MainThread) [custom_components.gardena_smart_system.switch] Getting Power socket state
2021-09-03 17:45:04 DEBUG (MainThread) [custom_components.gardena_smart_system.switch] Power socket has activity FOREVER_ON
2021-09-03 17:45:08 DEBUG (Thread-3) [gardena.smart_system] Received POWER_SOCKET message
2021-09-03 17:45:08 DEBUG (Thread-3) [gardena.smart_system] ------- Beginning of message ---------
2021-09-03 17:45:08 DEBUG (Thread-3) [gardena.smart_system] {"id":"28fa6df0-2a6d-4443-82a2-f3aa6b16c655","type":"POWER_SOCKET","attributes":{"activity":{"value":"OFF","timestamp":"2021-09-03T15:45:07.733+0000"},"state":{"value":"OK","timestamp":"2021-08-30T17:45:56.389+0000"}}}
2021-09-03 17:45:08 DEBUG (Thread-3) [gardena.smart_system] ------- End of message ---------
2021-09-03 17:45:08 DEBUG (Thread-3) [gardena.smart_system] Received COMMON message
2021-09-03 17:45:08 DEBUG (Thread-3) [gardena.smart_system] ------- Beginning of message ---------
2021-09-03 17:45:08 DEBUG (Thread-3) [gardena.smart_system] {"id":"28fa6df0-2a6d-4443-82a2-f3aa6b16c655","type":"COMMON","attributes":{"name":{"value":"SPower1"},"batteryState":{"value":"NO_BATTERY"},"rfLinkLevel":{"value":80,"timestamp":"2021-09-03T15:33:44.671+0000"},"serial":{"value":"00029416"},"modelType":{"value":"GARDENA smart Power"},"rfLinkState":{"value":"ONLINE"}}}
2021-09-03 17:45:08 DEBUG (Thread-3) [gardena.smart_system] ------- End of message ---------
2021-09-03 17:45:08 DEBUG (MainThread) [custom_components.gardena_smart_system.switch] Running Gardena update
2021-09-03 17:45:08 DEBUG (MainThread) [custom_components.gardena_smart_system.switch] Power socket has state OK
2021-09-03 17:45:08 DEBUG (MainThread) [custom_components.gardena_smart_system.switch] Getting Power socket state
2021-09-03 17:45:08 DEBUG (MainThread) [custom_components.gardena_smart_system.switch] Power socket has activity OFF
2021-09-03 17:45:11 DEBUG (Thread-3) [gardena.smart_system] Received POWER_SOCKET message
2021-09-03 17:45:11 DEBUG (Thread-3) [gardena.smart_system] ------- Beginning of message ---------
2021-09-03 17:45:11 DEBUG (Thread-3) [gardena.smart_system] {"id":"28fa6df0-2a6d-4443-82a2-f3aa6b16c655","type":"POWER_SOCKET","attributes":{"activity":{"value":"FOREVER_ON","timestamp":"2021-09-03T15:45:10.801+0000"},"state":{"value":"OK","timestamp":"2021-08-30T17:45:56.389+0000"}}}
2021-09-03 17:45:11 DEBUG (Thread-3) [gardena.smart_system] ------- End of message ---------
2021-09-03 17:45:11 DEBUG (Thread-3) [gardena.smart_system] Received COMMON message
2021-09-03 17:45:11 DEBUG (Thread-3) [gardena.smart_system] ------- Beginning of message ---------
2021-09-03 17:45:11 DEBUG (Thread-3) [gardena.smart_system] {"id":"28fa6df0-2a6d-4443-82a2-f3aa6b16c655","type":"COMMON","attributes":{"name":{"value":"SPower1"},"batteryState":{"value":"NO_BATTERY"},"rfLinkLevel":{"value":80,"timestamp":"2021-09-03T15:33:44.671+0000"},"serial":{"value":"00029416"},"modelType":{"value":"GARDENA smart Power"},"rfLinkState":{"value":"ONLINE"}}}
2021-09-03 17:45:11 DEBUG (Thread-3) [gardena.smart_system] ------- End of message ---------
2021-09-03 17:45:11 DEBUG (MainThread) [custom_components.gardena_smart_system.switch] Running Gardena update
2021-09-03 17:45:11 DEBUG (MainThread) [custom_components.gardena_smart_system.switch] Power socket has state OK
2021-09-03 17:45:11 DEBUG (MainThread) [custom_components.gardena_smart_system.switch] Getting Power socket state
2021-09-03 17:45:11 DEBUG (MainThread) [custom_components.gardena_smart_system.switch] Power socket has activity FOREVER_ON
2021-09-03 17:53:36 DEBUG (Thread-3) [gardena.smart_system] Received MOWER message
2021-09-03 17:53:36 DEBUG (Thread-3) [gardena.smart_system] ------- Beginning of message ---------
2021-09-03 17:53:36 DEBUG (Thread-3) [gardena.smart_system] {"id":"b56a3819-0053-49ff-b55d-bf50ba8fa2eb:cbtg","type":"MOWER","attributes":{"state":{"value":"OK","timestamp":"2021-09-03T15:25:34.197+0000"},"activity":{"value":"OK_CUTTING_TIMER_OVERRIDDEN","timestamp":"2021-09-03T15:25:34.197+0000"},"operatingHours":{"value":326}}}
2021-09-03 17:53:36 DEBUG (Thread-3) [gardena.smart_system] ------- End of message ---------
2021-09-03 17:53:36 DEBUG (Thread-3) [gardena.smart_system] Received COMMON message
2021-09-03 17:53:36 DEBUG (Thread-3) [gardena.smart_system] ------- Beginning of message ---------
2021-09-03 17:53:36 DEBUG (Thread-3) [gardena.smart_system] {"id":"b56a3819-0053-49ff-b55d-bf50ba8fa2eb","type":"COMMON","attributes":{"name":{"value":"Shaun"},"batteryLevel":{"value":70,"timestamp":"2021-09-03T15:53:35.601+0000"},"batteryState":{"value":"OK","timestamp":"2021-09-03T15:25:34.197+0000"},"rfLinkLevel":{"value":100,"timestamp":"2021-09-03T15:23:09.413+0000"},"serial":{"value":"201786033"},"modelType":{"value":"GARDENA smart Mower"},"rfLinkState":{"value":"ONLINE"}}}
2021-09-03 17:53:36 DEBUG (Thread-3) [gardena.smart_system] ------- End of message ---------
2021-09-03 17:53:36 DEBUG (MainThread) [custom_components.gardena_smart_system.vacuum] Running Gardena update
2021-09-03 17:53:36 DEBUG (MainThread) [custom_components.gardena_smart_system.vacuum] Mower has state OK
2021-09-03 17:53:36 DEBUG (MainThread) [custom_components.gardena_smart_system.vacuum] Getting mower state
2021-09-03 17:53:36 DEBUG (MainThread) [custom_components.gardena_smart_system.vacuum] Mower has activity OK_CUTTING_TIMER_OVERRIDDEN
2021-09-03 17:54:46 ERROR (Thread-3) [gardena.smart_system] error : [Errno 54] Connection reset by peer
2021-09-03 17:54:46 ERROR (Thread-3) [websocket] error from callback <bound method Client.on_close of <gardena.smart_system.Client object at 0x809e06730>>: on_close() missing 2 required positional arguments: 'close_status_code' and 'close_msg'

> Logger: gardena.smart_system
Source: /usr/local/share/homeassistant/lib/python3.8/site-packages/gardena/smart_system.py:32
First occurred: 17:54:46 (1 occurrences)
Last logged: 17:54:46
error : [Errno 54] Connection reset by peer

> Logger: websocket
Source: /usr/local/share/homeassistant/lib/python3.8/site-packages/websocket/_logging.py:66
First occurred: 17:54:46 (1 occurrences)
Last logged: 17:54:46
error from callback <bound method Client.on_close of <gardena.smart_system.Client object at 0x809e06730>>: on_close() missing 2 required positional arguments: 'close_status_code' and 'close_msg'


After that no updates anymore and the socket switch worked one last time.

**Comment by erikkt** [comment]
> I also installed 0.2.5b3 and after a restart everything seemed to work. I was able to switch one of my sockets on/off multiple times and its state got updated and my mower also sent its state. But some minutes later again no updates. Here is the log of it:
> 
> > 2021-09-03 17:44:46 INFO (MainThread) [custom_components.hacs] Stage changed: HacsStage.RUNNING
> > 2021-09-03 17:44:59 DEBUG (Thread-3) [gardena.smart_system] Received POWER_SOCKET message
> > 2021-09-03 17:44:59 DEBUG (Thread-3) [gardena.smart_system] ------- Beginning of message ---------
> > 2021-09-03 17:44:59 DEBUG (Thread-3) [gardena.smart_system] {"id":"28fa6df0-2a6d-4443-82a2-f3aa6b16c655","type":"POWER_SOCKET","attributes":{"activity":{"value":"OFF","timestamp":"2021-09-03T15:44:59.595+0000"},"state":{"value":"OK","timestamp":"2021-08-30T17:45:56.389+0000"}}}
> > 2021-09-03 17:44:59 DEBUG (Thread-3) [gardena.smart_system] ------- End of message ---------
> > 2021-09-03 17:44:59 DEBUG (Thread-3) [gardena.smart_system] Received COMMON message
> > 2021-09-03 17:44:59 DEBUG (Thread-3) [gardena.smart_system] ------- Beginning of message ---------
> > 2021-09-03 17:44:59 DEBUG (Thread-3) [gardena.smart_system] {"id":"28fa6df0-2a6d-4443-82a2-f3aa6b16c655","type":"COMMON","attributes":{"name":{"value":"SPower1"},"batteryState":{"value":"NO_BATTERY"},"rfLinkLevel":{"value":80,"timestamp":"2021-09-03T15:33:44.671+0000"},"serial":{"value":"[00029416](tel:00029416)"},"modelType":{"value":"GARDENA smart Power"},"rfLinkState":{"value":"ONLINE"}}}
> > 2021-09-03 17:44:59 DEBUG (Thread-3) [gardena.smart_system] ------- End of message ---------
> > 2021-09-03 17:44:59 DEBUG (MainThread) [custom_components.gardena_smart_system.switch] Running Gardena update
> > 2021-09-03 17:44:59 DEBUG (MainThread) [custom_components.gardena_smart_system.switch] Power socket has state OK
> > 2021-09-03 17:44:59 DEBUG (MainThread) [custom_components.gardena_smart_system.switch] Getting Power socket state
> > 2021-09-03 17:44:59 DEBUG (MainThread) [custom_components.gardena_smart_system.switch] Power socket has activity OFF
> > 2021-09-03 17:45:04 DEBUG (Thread-3) [gardena.smart_system] Received POWER_SOCKET message
> > 2021-09-03 17:45:04 DEBUG (Thread-3) [gardena.smart_system] ------- Beginning of message ---------
> > 2021-09-03 17:45:04 DEBUG (Thread-3) [gardena.smart_system] {"id":"28fa6df0-2a6d-4443-82a2-f3aa6b16c655","type":"POWER_SOCKET","attributes":{"activity":{"value":"FOREVER_ON","timestamp":"2021-09-03T15:45:03.947+0000"},"state":{"value":"OK","timestamp":"2021-08-30T17:45:56.389+0000"}}}
> > 2021-09-03 17:45:04 DEBUG (Thread-3) [gardena.smart_system] ------- End of message ---------
> > 2021-09-03 17:45:04 DEBUG (Thread-3) [gardena.smart_system] Received COMMON message
> > 2021-09-03 17:45:04 DEBUG (Thread-3) [gardena.smart_system] ------- Beginning of message ---------
> > 2021-09-03 17:45:04 DEBUG (Thread-3) [gardena.smart_system] {"id":"28fa6df0-2a6d-4443-82a2-f3aa6b16c655","type":"COMMON","attributes":{"name":{"value":"SPower1"},"batteryState":{"value":"NO_BATTERY"},"rfLinkLevel":{"value":80,"timestamp":"2021-09-03T15:33:44.671+0000"},"serial":{"value":"[00029416](tel:00029416)"},"modelType":{"value":"GARDENA smart Power"},"rfLinkState":{"value":"ONLINE"}}}
> > 2021-09-03 17:45:04 DEBUG (Thread-3) [gardena.smart_system] ------- End of message ---------
> > 2021-09-03 17:45:04 DEBUG (MainThread) [custom_components.gardena_smart_system.switch] Running Gardena update
> > 2021-09-03 17:45:04 DEBUG (MainThread) [custom_components.gardena_smart_system.switch] Power socket has state OK
> > 2021-09-03 17:45:04 DEBUG (MainThread) [custom_components.gardena_smart_system.switch] Getting Power socket state
> > 2021-09-03 17:45:04 DEBUG (MainThread) [custom_components.gardena_smart_system.switch] Power socket has activity FOREVER_ON
> > 2021-09-03 17:45:08 DEBUG (Thread-3) [gardena.smart_system] Received POWER_SOCKET message
> > 2021-09-03 17:45:08 DEBUG (Thread-3) [gardena.smart_system] ------- Beginning of message ---------
> > 2021-09-03 17:45:08 DEBUG (Thread-3) [gardena.smart_system] {"id":"28fa6df0-2a6d-4443-82a2-f3aa6b16c655","type":"POWER_SOCKET","attributes":{"activity":{"value":"OFF","timestamp":"2021-09-03T15:45:07.733+0000"},"state":{"value":"OK","timestamp":"2021-08-30T17:45:56.389+0000"}}}
> > 2021-09-03 17:45:08 DEBUG (Thread-3) [gardena.smart_system] ------- End of message ---------
> > 2021-09-03 17:45:08 DEBUG (Thread-3) [gardena.smart_system] Received COMMON message
> > 2021-09-03 17:45:08 DEBUG (Thread-3) [gardena.smart_system] ------- Beginning of message ---------
> > 2021-09-03 17:45:08 DEBUG (Thread-3) [gardena.smart_system] {"id":"28fa6df0-2a6d-4443-82a2-f3aa6b16c655","type":"COMMON","attributes":{"name":{"value":"SPower1"},"batteryState":{"value":"NO_BATTERY"},"rfLinkLevel":{"value":80,"timestamp":"2021-09-03T15:33:44.671+0000"},"serial":{"value":"[00029416](tel:00029416)"},"modelType":{"value":"GARDENA smart Power"},"rfLinkState":{"value":"ONLINE"}}}
> > 2021-09-03 17:45:08 DEBUG (Thread-3) [gardena.smart_system] ------- End of message ---------
> > 2021-09-03 17:45:08 DEBUG (MainThread) [custom_components.gardena_smart_system.switch] Running Gardena update
> > 2021-09-03 17:45:08 DEBUG (MainThread) [custom_components.gardena_smart_system.switch] Power socket has state OK
> > 2021-09-03 17:45:08 DEBUG (MainThread) [custom_components.gardena_smart_system.switch] Getting Power socket state
> > 2021-09-03 17:45:08 DEBUG (MainThread) [custom_components.gardena_smart_system.switch] Power socket has activity OFF
> > 2021-09-03 17:45:11 DEBUG (Thread-3) [gardena.smart_system] Received POWER_SOCKET message
> > 2021-09-03 17:45:11 DEBUG (Thread-3) [gardena.smart_system] ------- Beginning of message ---------
> > 2021-09-03 17:45:11 DEBUG (Thread-3) [gardena.smart_system] {"id":"28fa6df0-2a6d-4443-82a2-f3aa6b16c655","type":"POWER_SOCKET","attributes":{"activity":{"value":"FOREVER_ON","timestamp":"2021-09-03T15:45:10.801+0000"},"state":{"value":"OK","timestamp":"2021-08-30T17:45:56.389+0000"}}}
> > 2021-09-03 17:45:11 DEBUG (Thread-3) [gardena.smart_system] ------- End of message ---------
> > 2021-09-03 17:45:11 DEBUG (Thread-3) [gardena.smart_system] Received COMMON message
> > 2021-09-03 17:45:11 DEBUG (Thread-3) [gardena.smart_system] ------- Beginning of message ---------
> > 2021-09-03 17:45:11 DEBUG (Thread-3) [gardena.smart_system] {"id":"28fa6df0-2a6d-4443-82a2-f3aa6b16c655","type":"COMMON","attributes":{"name":{"value":"SPower1"},"batteryState":{"value":"NO_BATTERY"},"rfLinkLevel":{"value":80,"timestamp":"2021-09-03T15:33:44.671+0000"},"serial":{"value":"[00029416](tel:00029416)"},"modelType":{"value":"GARDENA smart Power"},"rfLinkState":{"value":"ONLINE"}}}
> > 2021-09-03 17:45:11 DEBUG (Thread-3) [gardena.smart_system] ------- End of message ---------
> > 2021-09-03 17:45:11 DEBUG (MainThread) [custom_components.gardena_smart_system.switch] Running Gardena update
> > 2021-09-03 17:45:11 DEBUG (MainThread) [custom_components.gardena_smart_system.switch] Power socket has state OK
> > 2021-09-03 17:45:11 DEBUG (MainThread) [custom_components.gardena_smart_system.switch] Getting Power socket state
> > 2021-09-03 17:45:11 DEBUG (MainThread) [custom_components.gardena_smart_system.switch] Power socket has activity FOREVER_ON
> > 2021-09-03 17:53:36 DEBUG (Thread-3) [gardena.smart_system] Received MOWER message
> > 2021-09-03 17:53:36 DEBUG (Thread-3) [gardena.smart_system] ------- Beginning of message ---------
> > 2021-09-03 17:53:36 DEBUG (Thread-3) [gardena.smart_system] {"id":"b56a3819-0053-49ff-b55d-bf50ba8fa2eb:cbtg","type":"MOWER","attributes":{"state":{"value":"OK","timestamp":"2021-09-03T15:25:34.197+0000"},"activity":{"value":"OK_CUTTING_TIMER_OVERRIDDEN","timestamp":"2021-09-03T15:25:34.197+0000"},"operatingHours":{"value":326}}}
> > 2021-09-03 17:53:36 DEBUG (Thread-3) [gardena.smart_system] ------- End of message ---------
> > 2021-09-03 17:53:36 DEBUG (Thread-3) [gardena.smart_system] Received COMMON message
> > 2021-09-03 17:53:36 DEBUG (Thread-3) [gardena.smart_system] ------- Beginning of message ---------
> > 2021-09-03 17:53:36 DEBUG (Thread-3) [gardena.smart_system] {"id":"b56a3819-0053-49ff-b55d-bf50ba8fa2eb","type":"COMMON","attributes":{"name":{"value":"Shaun"},"batteryLevel":{"value":70,"timestamp":"2021-09-03T15:53:35.601+0000"},"batteryState":{"value":"OK","timestamp":"2021-09-03T15:25:34.197+0000"},"rfLinkLevel":{"value":100,"timestamp":"2021-09-03T15:23:09.413+0000"},"serial":{"value":"201786033"},"modelType":{"value":"GARDENA smart Mower"},"rfLinkState":{"value":"ONLINE"}}}
> > 2021-09-03 17:53:36 DEBUG (Thread-3) [gardena.smart_system] ------- End of message ---------
> > 2021-09-03 17:53:36 DEBUG (MainThread) [custom_components.gardena_smart_system.vacuum] Running Gardena update
> > 2021-09-03 17:53:36 DEBUG (MainThread) [custom_components.gardena_smart_system.vacuum] Mower has state OK
> > 2021-09-03 17:53:36 DEBUG (MainThread) [custom_components.gardena_smart_system.vacuum] Getting mower state
> > 2021-09-03 17:53:36 DEBUG (MainThread) [custom_components.gardena_smart_system.vacuum] Mower has activity OK_CUTTING_TIMER_OVERRIDDEN
> > 2021-09-03 17:54:46 ERROR (Thread-3) [gardena.smart_system] error : [Errno 54] Connection reset by peer
> > 2021-09-03 17:54:46 ERROR (Thread-3) [websocket] error from callback <bound method Client.on_close of <gardena.smart_system.Client object at 0x809e06730>>: on_close() missing 2 required positional arguments: 'close_status_code' and 'close_msg'
> 
> > Logger: gardena.smart_system
> > Source: /usr/local/share/homeassistant/lib/python3.8/site-packages/gardena/smart_system.py:32
> > First occurred: 17:54:46 (1 occurrences)
> > Last logged: 17:54:46
> > error : [Errno 54] Connection reset by peer
> 
> > Logger: websocket
> > Source: /usr/local/share/homeassistant/lib/python3.8/site-packages/websocket/_logging.py:66
> > First occurred: 17:54:46 (1 occurrences)
> > Last logged: 17:54:46
> > error from callback <bound method Client.on_close of <gardena.smart_system.Client object at 0x809e06730>>: on_close() missing 2 required positional arguments: 'close_status_code' and 'close_msg'
> 
> After that no updates anymore and the socket switch worked one last time.

I have exact same issue as this.

**Comment by fjepsen** [comment]
I am sorry but I have no knowlege of programming/installing/updating python but I think the problem is a rather old version of websocket (websocket_client-0.58.0) installed on my Homeassistant on TrueNAS. In this version the on_close sometimes returns no args. 
I tried to update Homeassistant and HACS and got now HA 2021.9.2 and HACS 1.15.2. Some site-packages were updated but not websocket. I see py_smart_gardena-0.8.2 installed and in GIT I saw a requirement of websocket-client==1.1.0 but this requirement got not fullfilled. 

Perhaps somebody with more insight in the install/update mechanisms of homeassistant/HACS/python can tell what to do.

To fix it for me I made the following quick change in /usr/local/share/homeassistant/lib/python3.8/site-packages/websocket/_app.py:
```
    def _get_close_args(self, data):
        """
        _get_close_args extracts the code, reason from the close body
        if they exists, and if the self.on_close except three arguments
        """
        # if the on_close callback is "old", just return empty list
        if sys.version_info < (3, 0):
            if not self.on_close or len(inspect.getargspec(self.on_close).args) != 3:
                return []
        else:
            if not self.on_close or len(inspect.getfullargspec(self.on_close).args) != 3:
-                return []
+                return [None, None]

        if data and len(data) >= 2:
            code = 256 * six.byte2int(data[0:1]) + six.byte2int(data[1:2])
            reason = data[2:].decode('utf-8')
            return [code, reason]

        return [None, None]
```
This fixed the immediate problem and I am still able communicate with gardenasystem even after a "connection reset by peer".

**Comment by erikkt** [comment]
I still get:
 `2021-09-07 09:00:14 ERROR (Thread-4) [websocket] error from callback <bound method Client.on_message of <gardena.smart_system.Client object at 0x7f0bdc5f0580>>: on_message() missing 1 required positional argument: 'message'
`
@fjepsen Any workaround for this?

**Comment by fjepsen** [comment]
What is your version of websockets?
Best would be to update [websocket-client](https://github.com/websocket-client/websocket-client).
But I don't know how to do this manually.
Thought this should be done automatically.
I hoped somebody here could tell me more.

**Comment by rangulvers** [comment]
I keep running into the same issue with 
` 
OS Version:               Home Assistant OS 7.5
Home Assistant Core:      2022.3.5
hass-gardena-smart-system 0.2.3
`

after I reboot my HA the sensor for my Sileno is updated correctly once. After this no more updates are received


`
2022-03-20 22:02:04 ERROR (Thread-3) [websocket] error from callback <bound method Client.on_open of <gardena.smart_system.Client object at 0x7f731b3fd0>>: on_open() takes 1 positional argument but 2 were given
2022-03-20 22:02:04 ERROR (Thread-3) [websocket] error from callback <bound method Client.on_error of <gardena.smart_system.Client object at 0x7f731b3fd0>>: on_error() takes 2 positional arguments but 3 were given
2022-03-20 22:02:04 ERROR (Thread-3) [root] Uncaught thread exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/websocket/_app.py", line 424, in _callback
    callback(self, *args)
TypeError: on_open() takes 1 positional argument but 2 were given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/websocket/_app.py", line 336, in run_forever
    self._callback(self.on_open)
  File "/usr/local/lib/python3.9/site-packages/websocket/_app.py", line 429, in _callback
    self.on_error(self, e)
TypeError: on_error() takes 2 positional arguments but 3 were given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/websocket/_app.py", line 424, in _callback
    callback(self, *args)
TypeError: on_error() takes 2 positional arguments but 3 were given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.9/site-packages/websocket/_app.py", line 386, in run_forever
    self._callback(self.on_error, e)
  File "/usr/local/lib/python3.9/site-packages/websocket/_app.py", line 429, in _callback
    self.on_error(self, e)
TypeError: on_error() takes 2 positional arguments but 3 were given
`

**Comment by buentead** [comment]
Same on my installation. I'm running:
```
OS Version:               Home Assistant OS 7.56
Home Assistant Core:      2022.4.3
hass-gardena-smart-system 0.2.3
```
After rebooting HA the Gardena sensor is updated once. After this no more updates are received. The log shows the following entry once.
```
Logger: websocket
Source: /usr/local/lib/python3.9/site-packages/websocket/_logging.py:62
First occurred: April 13, 2022, 22:03:53 (2 occurrences)
Last logged: April 13, 2022, 22:03:53

error from callback <bound method Client.on_open of <gardena.smart_system.Client object at 0x7fa1bae9a0>>: on_open() takes 1 positional argument but 2 were given
error from callback <bound method Client.on_error of <gardena.smart_system.Client object at 0x7fa1bae9a0>>: on_error() takes 2 positional arguments but 3 were given
```

**Comment by tobiasbayer** [comment]
Same here. Also see https://github.com/py-smart-gardena/hass-gardena-smart-system/issues/100

**Comment by buentead** [comment]
I updated to version 0.2.5b4 and my water control and floor sensor works fine now (since 24 hours). 

This is my actual set up:
```
OS Version:               Home Assistant OS 7.6
Home Assistant Core:      2022.4.4
hass-gardena-smart-system 0.2.5b4
Board:                    rpi4-64
```

**Comment by grm** [comment]
Hello,

there has been a lot of changes reecently in the library.
Could you give it another shot please and recreate a ticket if you still have an issue ?

Thx
